%% Automatic Parking Valet with Unreal Engine Simulation
% This example demonstrates the design of a hybrid controller for an automatic 
% searching and parking task. You will learn how to combine adaptive model predictive 
% control (MPC) with reinforcement learning (RL) to perform a parking maneuver. 
% Unreal Engine® is used for environment perception and visualization.
% 
 parallel.gpu.enableCUDAForwardCompatibility(true)
% 
% The control objective is to park the vehicle in an empty spot after starting 
% from an initial pose. The control algorithm executes a series of maneuvers while 
% sensing and avoiding obstacles in tight spaces. It switches between an adaptive 
% MPC controller and a reinforcement learning agent to complete the parking maneuver. 
% 
% The adaptive MPC controller moves the vehicle at a constant speed along a 
% reference path while searching for an empty parking spot. When a spot is found, 
% the reinforcement learning agent takes over and executes a parking maneuver 
% according to its pretrained policy. Prior knowledge of the environment (the 
% parking lot) including the locations of the empty spots and parked vehicles 
% is available to both controllers.
%% Parking Lot
% The parking lot environment used in this example is a subsection of the <docid:driving_ref#mw_8ecb60fe-eb82-4f45-9629-a581750c6b69 
% Large Parking Lot> scene. The |ParkingLotManager| object stores information 
% on the ego vehicle, empty parking spots, and static obstacles (parked cars and 
% boundaries), while the ParkingLotVisualizer object creates a 2-D visualization 
% of the scene. In the 2-D visualization, each parking spot has a unique index 
% number and an indicator light that is either green (free) or red (occupied). 
% Parked vehicles are represented in black.
% 
% 
% 
% Specify a sample time $T_s$ (seconds) for the controllers and a simulation 
% time $T_f$ (seconds).

Ts = 0.1;
Tf = 50;
%% 
% Create a reference path for the ego vehicle using the |createReferenceTrajectory| 
% method of the |ParkingLotManager| object. The reference path starts from the 
% southeast corner of the parking lot and ends at the western edge as displayed 
% with the dashed pink line.

parkingLot = ParkingLotManager;
xRef = parkingLot.createReferenceTrajectory(Ts,Tf);
info = parkingLot.getInfo();
%% 
% Set the parking space at index 18 as the free spot and fill all the other 
% spots with static vehicle actors.

freeSpotIndex = 18;
mdl = "rlAutoParkingValet3D";
setupActorVehicles(mdl,freeSpotIndex);
%% 
% Create a |ParkingLotVisualizer| object with a free spot at index 18 and the 
% specified reference path |xRef|. Enable the visualizer figure's |Visible| property 
% so that it opens outside the live script.

visualizer = ParkingLotVisualizer(freeSpotIndex,Ts,Tf);
set(gcf,Visible="on");
%% 
% Specify an initial pose $\left(X_0 ,Y_0 ,\theta_0 \right)$ for the ego vehicle. 
% The units of $X_0$ and $Y_0$ are meters and $\theta_0$ is in radians.

egoInitialPose = [40 -55 pi/2];
%% 
% Compute the target pose for the vehicle using the |findGoalPose| method of 
% the |ParkingLotManager| object. The goal pose corresponds to the location in 
% |freeSpotIdx|.

vehiclePose = [10 -32.5 pi];
egoTargetPose = parkingLot.findGoalPose(vehiclePose,freeSpotIndex);
%% Sensor Modules
% The parking algorithm uses a geometric "mode selector" object to scan for 
% available parking spots and a lidar sensor to generate detections from the environment.
% Mode Selector
% The mode selector system scans a conical area in front of the vehicle for 
% free parking spots. The scanning area is represented by the area shaded in green 
% in the following figure. The camera has a field of view $\varphi$ bounded by 
% $\pm$60 degrees and a maximum measurement depth $d_{\max }$ of 10 m (equal to 
% |searchDist|). 

searchDist = 10;
%% 
% As the ego vehicle moves forward, the mode selector system senses the parking 
% spots within the field of view and determines whether a spot is free or occupied. 
% For simplicity, this action is implemented using geometrical relationships between 
% the spot locations and the current vehicle pose. A parking spot is within the 
% scanning range if $d_i \le d_{\max }$ and $\varphi_{\min } \le \varphi_i \le 
% \varphi_{\max }$, where $d_i$ is the distance to the parking spot and $\varphi_i$ 
% is the angle to the parking spot. Once a free parking spot is identified within 
% the scanning area, the vehicle switches from the path-following adaptive MPC 
% controller to the RL controller used to execute the parking maneuver.
% 
% 
% Lidar
% A <docid:driving_ref#mw_f17d49dd-d3d9-40fb-b1cc-2e35dfdf5302 Simulation 3D 
% Lidar> block is used to generate a point cloud of detections from the environment. 
% The lidar is mounted to the roof center and has a horizontal field-of-view (FOV) 
% of 360 degrees and a vertical FOV of 40 degrees.The point cloud generated by 
% the lidar contains five channels. The first three channels contain the $X$, 
% $Y$, and $Z$ position, in meters, of each detection relative to the sensor. 
% In the lidar sensor's coordinate system, the _X_-axis extends forward from the 
% vehicle, the _Y_-axis extends to the left of the vehicle (as viewed when looking 
% in the forward direction of the vehicle), and the _Z_-axis points up. The fourth 
% channel of the point cloud contains the straight-line distance to each detection 
% in meters. The fifth channel contains the reflectivity of each detection, normalized 
% in the range [0,1]. The reinforcement learning agent uses this point cloud data 
% to understand its environment.
% 
% 
%% Auto Parking Valet Model
% Load the automatic parking valet parameters.

autoParkingValetParams3D
%% 
% The parking valet model, including the controllers, ego vehicle, sensors, 
% and parking lot, is implemented as a Simulink® model. Open the model.

open_system(mdl)
%% 
% 
% 
% In this model:
%% 
% * The vehicle is modeled in the Vehicle Dynamics and Sensing subsystem. The 
% vehicle kinematics are modeled using a single-track bicycle kinematics model 
% with two input signals, vehicle speed $v$ (m/s) and steering angle $\delta$ 
% (radians).
% * The adaptive MPC and RL agent blocks are found in the MPC Tracking Controller 
% and RL Controller subsystems, respectively.
% * Mode switching between the controllers is handled by the Vehicle Mode Selector 
% subsystem, which outputs an "isParking" signal indicating whether the vehicle 
% is actively making a parking maneuver. Initially, the vehicle is in search mode 
% and the adaptive MPC controller tracks the reference path. When a free spot 
% is found, the "isParking" signal activates the RL Agent to perform the parking 
% maneuver.
% * The Unreal Engine Visualization and Sensing subsystem handles animation 
% of the environment. You can choose to enable Unreal Engine visualization and/or 
% 3-D point cloud visualization. Double-click this subsystem to specify the visualization 
% options.
%% 
% 
% 
% Unreal Engine visualization can slow down the simulation, so the |Enable Unreal 
% Engine visualization| parameter is automatically disabled when training the 
% agent.
%% Adaptive Model Predictive Controller Design
% Create the adaptive MPC controller object for reference trajectory tracking 
% using the |createMPCForParking3D| script. For more information on adaptive MPC, 
% see <docid:mpc_ug#bujlmiz Adaptive MPC>.

createMPCForParking3D;
%% Reinforcement Learning Controller Design
% To train the reinforcement learning agent, you must create an environment 
% interface and an agent object.
% Create Environment
% The environment for training is defined as a rectangular area surrounding 
% the free parking spot, visualized by the region shaded in red in the following 
% figure. Constraining the training to this region significantly reduces training 
% duration when compared to training over the entire parking lot area. 
% 
% The free spot selected for each training episode is randomly selected from 
% one of four spot locations, with two on each side of the isle. This randomization 
% is done to make the agent more robust to different vehicle shapes, sizes, colors, 
% and lighting.
% 
% 
% 
% For this environment:
%% 
% * The training region is a 13.625 m x 12.34 m space with the target spot at 
% its horizontal center.
% * The observations are the position errors $X_e$ and $Y_e$ of the ego vehicle 
% with respect to the target pose, the heading angle error $\theta_e$, and the 
% five-channel lidar point cloud. The position and heading error observations 
% are scaled to the range [-1, 1] and the lidar data is scaled to the range [0, 
% 1].
% * The vehicle speed during training varies randomly between 1 and 4 m/s each 
% episode and is held constant for the entire episode.
% * The action signal is a continuous steering angle that ranges between +/- 
% $\pi /4$ radians.
% * The vehicle is considered parked if the errors with respect to target pose 
% are within specified tolerances of +/- 0.75 m (position) and +/-10 degrees (heading).
% * The episode is terminated if the ego vehicle parks successfully, leaves 
% the training region, or collides with an obstacle.
%% 
% The reward $r_t$ provided at time _t_, is:
% 
% $$r_t =2e^{-\left(0\ldotp 05{X_e }^2 +0\ldotp 04{Y_e }^2 \right)} +0\ldotp 
% 5e^{-40{\theta_e }^2 } -0\ldotp 05\delta^2 +100f_t -50g_t$$
% 
% Here, $X_e$, $Y_e$, and $\theta_e$ are the position and heading angle errors 
% of the ego vehicle from the target pose, while $\delta$ is the steering angle. 
% $f_t$ (0 or 1) indicates whether the vehicle has parked and $g_t$ (0 or 1) indicates 
% if the vehicle has collided with an obstacle or left the training region at 
% time $t$.
% 
% Create the observation specifications for the environment using the Simulink 
% bus object stored in |ObservationBus.mat|.

load("ObservationBus.mat","ObservationBus")
obsInfo = bus2RLSpec("ObservationBus");
obsNames = [obsInfo(1).Name, obsInfo(2).Name];
%% 
% Create the action specifications for the environment.

nAct = 1;
actInfo = rlNumericSpec([nAct 1],LowerLimit=-1,UpperLimit=1);
actNames = "actionInput";
%% 
% Specify the path to the RL Agent block and create the Simulink environment 
% interface.

agentBlock = mdl + "/Controller/RL Controller/RL Agent";
env = rlSimulinkEnv( ...
    mdl, ...
    agentBlock, ...
    obsInfo, ...
    actInfo, ...
    UseFastRestart="on");

%% 
% Specify a reset function for training. The |autoParkingValetResetFcn3D| function 
% randomly resets the initial pose of the ego vehicle at the start of each episode.

env.ResetFcn = @autoParkingValetResetFcn3D;
%% 
% For more information on creating Simulink environments, see <docid:rl_ref#mw_12cc40dc-3191-4a23-af71-1625696c1a14 
% |rlSimulinkEnv|>.
% Create Agent
% The agent in this example is a twin-delayed deep deterministic policy gradient 
% (TD3) agent. TD3 agents rely on actor and critic approximator objects to learn 
% the optimal policy. To learn more about TD3 agents, see <docid:rl_ug#mw_3a8116dc-284e-4d85-a31c-0921ec03916e 
% Twin-Delayed Deep Deterministic Policy Gradient Agents>.
% 
% The actor and critic networks are initialized randomly. Ensure reproducibility 
% by fixing the seed of the random generator.

rng(0)
% Create Critics
% TD3 agents use two parameterized Q-value function approximators to estimate 
% the value of the policy. The output of the critic network is the state-action 
% value function for a taking a given action from a given observation.
% 
% Define each network path as an array of layer objects and assign names to 
% the input and output layers of each path. These names allow you to connect the 
% paths and then later explicitly associate the network input and output layers 
% with the appropriate environment channel.

% Lidar path
lidarPath = [
    imageInputLayer( ...
        obsInfo(2).Dimension, ...
        Name="lidarData", ...
        Normalization="none")
    convolution2dLayer([5 5],8,Padding="same")
    reluLayer
    maxPooling2dLayer([3 3],Padding="same",Stride=[3 3])
    convolution2dLayer([5 5],8,Padding="same")
    reluLayer
    maxPooling2dLayer([3 3],Padding="same",Stride=[3 3])
    flattenLayer
    tanhLayer
    fullyConnectedLayer(512)
    reluLayer
    fullyConnectedLayer(256,Name="lidar_fc")];

% Pose path
posePath = [
    featureInputLayer(obsInfo(1).Dimension(1),Name="poseInfo")
    fullyConnectedLayer(64,Name="pose_fc")];

% Action path
actionInput = [
    featureInputLayer(actInfo(1).Dimension(1),Name="actionInput")
    fullyConnectedLayer(32,Name="action_fc")];

% Concatenated path
mainPath = [
    concatenationLayer(1,3,Name="concat")
    reluLayer
    fullyConnectedLayer(256)
    reluLayer
    fullyConnectedLayer(128)
    reluLayer
    fullyConnectedLayer(1,Name="criticOutLyr")];

% Convert to layerGraph object and connect layers
criticNet = layerGraph(lidarPath);
criticNet = addLayers(criticNet,posePath);
criticNet = addLayers(criticNet,actionInput);
criticNet = addLayers(criticNet,mainPath);

criticNet = connectLayers(criticNet,"lidar_fc","concat/in1");
criticNet = connectLayers(criticNet,"pose_fc","concat/in2");
criticNet = connectLayers(criticNet,"action_fc","concat/in3");
%% 
% Convert to a <docid:nnet_ref#object_dlnetwork |dlnetwork|> object and display 
% information about the network including the number of learnable parameters and 
% information on the network inputs.

criticdlnet = dlnetwork(criticNet);
summary(criticdlnet)
%% 
% Create the critics using |criticdlnet|, the environment observation and action 
% specifications, and the names of the network input layers to be connected with 
% the environment observation and action channels. For more information see <docid:rl_ref#mw_e6e7abac-0a33-423b-8473-1409879db701 
% |rlQValueFunction|>.

critic = rlQValueFunction(criticdlnet,obsInfo,actInfo,...
    ObservationInputNames=obsNames, ActionInputNames=actNames);
% Create Actors
% Create the neural network for the actor. The output of the actor network is 
% the steering angle.

% Lidar path
lidarPath = [
    imageInputLayer( ...
        obsInfo(2).Dimension, ...
        Name="lidarData", ...
        Normalization="none")
    convolution2dLayer([5 5],8,Padding="same")
    reluLayer
    maxPooling2dLayer([3 3],Padding="same",Stride=[3 3])
    convolution2dLayer([5 5],8,Padding="same")
    reluLayer
    maxPooling2dLayer([3 3],Padding="same",Stride=[3 3])
    flattenLayer
    tanhLayer
    fullyConnectedLayer(512)
    reluLayer
    fullyConnectedLayer(256,Name="lidar_fc")];

% Pose path
posePath = [
    featureInputLayer(obsInfo(1).Dimension(1),Name="poseInfo")
    fullyConnectedLayer(64,Name="pose_fc")];

% Concatenated path
commonPath = [
    concatenationLayer(1,2,Name="concat")
    reluLayer
    fullyConnectedLayer(256)
    reluLayer
    fullyConnectedLayer(128)
    reluLayer(Name="commonOut")];

meanPath = fullyConnectedLayer(actInfo(1).Dimension(1),Name="meanOut");
stdPath = [
    fullyConnectedLayer(actInfo(1).Dimension(1),Name="stdOut_fc")
    softplusLayer(Name="stdOut")];

% Convert to layerGraph object and connect layers
actorNet = layerGraph(lidarPath);
actorNet = addLayers(actorNet,posePath);
actorNet = addLayers(actorNet,commonPath);
actorNet = addLayers(actorNet,meanPath);
actorNet = addLayers(actorNet,stdPath);

actorNet = connectLayers(actorNet,"lidar_fc","concat/in1");
actorNet = connectLayers(actorNet,"pose_fc","concat/in2");
actorNet = connectLayers(actorNet,"commonOut","meanOut");
actorNet = connectLayers(actorNet,"commonOut","stdOut_fc");
%% 
% Convert to a <docid:nnet_ref#object_dlnetwork |dlnetwork|> object and display 
% information about the network.

actordlnet = dlnetwork(actorNet);
summary(actordlnet)
%% 
% Create the actor object for the SAC agent. For more information see <docid:rl_ref#mw_c2909424-90f4-4a52-803b-73310483e6c3 
% |rlContinuousGaussianActor|>.

actor = rlContinuousGaussianActor(actordlnet,obsInfo,actInfo,...
    ActionMeanOutputNames="meanOut",ActionStandardDeviationOutputNames="stdOut");
%% 
% Specify the agent options and create the SAC agent. For more information on 
% SAC agent options, see <docid:rl_ref#mw_372ffd1e-e1d2-453c-a691-cfef5da40ef8 
% |rlSACAgentOptions|>.

agentOpts = rlSACAgentOptions(SampleTime=Ts, ...
    DiscountFactor=0.99, ...
    ExperienceBufferLength=1e6, ...
    MiniBatchSize=256);
%% 
% For this example, set the actor and critic learn rates to |1e-3|, respectively. 
% Set a gradient threshold factor of |1| to limit the gradients during training. 
% For more information, see <docid:rl_ref#mw_18a712bb-b821-4dd9-a7ad-460ad7f2aa03 
% |rlOptimizerOptions|>.
% 
% Specify training options for the actor.
% Mantener las tasas de aprendizaje (ya son altas), pero soltar el "freno" L2
agentOpts.ActorOptimizerOptions.LearnRate = 1e-3;
agentOpts.ActorOptimizerOptions.GradientThreshold = 1;
agentOpts.ActorOptimizerOptions.L2RegularizationFactor = 1e-3;
%% 
% Specify training options for the critic.

agentOpts.CriticOptimizerOptions(1).LearnRate = 1e-3;
agentOpts.CriticOptimizerOptions(1).GradientThreshold = 1;
%% 
% Create the agent. Change algorithmType to "DDPG" for Deep Deterministic Policy Gradient.

algorithmType = "DDPG";  % Change to "SAC" for Soft Actor-Critic

if strcmp(algorithmType, "DDPG")
    % Create deterministic actor for DDPG (reusing existing paths)
    commonPathDDPG = [
        concatenationLayer(1,2,Name="concat")
        reluLayer
        fullyConnectedLayer(256)
        reluLayer
        fullyConnectedLayer(128)
        reluLayer
        fullyConnectedLayer(actInfo(1).Dimension(1))
        tanhLayer(Name="actionOutput")];
    
    actorNetDDPG = layerGraph(lidarPath);
    actorNetDDPG = addLayers(actorNetDDPG, posePath);
    actorNetDDPG = addLayers(actorNetDDPG, commonPathDDPG);
    
    actorNetDDPG = connectLayers(actorNetDDPG, "lidar_fc", "concat/in1");
    actorNetDDPG = connectLayers(actorNetDDPG, "pose_fc", "concat/in2");
    
    actordlnetDDPG = dlnetwork(actorNetDDPG);
    actorDeterministic = rlContinuousDeterministicActor(actordlnetDDPG, obsInfo, actInfo);
    
    agentOptsDDPG = rlDDPGAgentOptions(SampleTime=Ts, DiscountFactor=0.99, ...
        ExperienceBufferLength=1e6, MiniBatchSize=256);
    agentOptsDDPG.ActorOptimizerOptions.LearnRate = 1e-4;
    agentOptsDDPG.CriticOptimizerOptions.LearnRate = 1e-3;
    
    agent = rlDDPGAgent(actorDeterministic, critic, agentOptsDDPG);
else
    % Create the agent using the actor, the critics, and the agent options objects.
    agent = rlSACAgent(actor,critic,agentOpts);
end

% Train Agent
% To train the agent, first specify the training options.
% 
% The agent is trained for a maximum of |10000| episodes with each episode lasting 
% a maximum of |200| time steps. The training terminates when the maximum number 
% of episodes is reached or the average reward over |200| episodes reaches a value 
% of |116| or greater. Specify the options for training using the <docid:rl_ref#mw_1f5122fe-cb3a-4c27-8c80-1ce46c013bf0 
% |rlTrainingOptions|> function.

% Define the directory for saving intermediate agents
saveDir = "savedAgents";
if ~exist(saveDir, "dir")
    mkdir(saveDir);
end

trainOpts = rlTrainingOptions(...
    MaxEpisodes=10000,...
    MaxStepsPerEpisode=200,...
    ScoreAveragingWindowLength=200,...
    Plots="training-progress",...
    StopTrainingCriteria="AverageReward",...
    StopTrainingValue=116,...
    UseParallel=true,...
    SaveAgentCriteria="AverageReward",...
    SaveAgentValue=100,...
    SaveAgentDirectory=saveDir);

% Train the agent using the <docid:rl_ref#mw_c0ccd38c-bbe6-4609-a87d-52ebe4767852 
% |train|> function. Fully training this agent is a computationally intensive 
% process that may take several hours to complete. To save time while running 
% this example, load a pretrained agent by setting |doTraining| to |false|. To 
% train the agent yourself, set |doTraining| to |true|.

doTraining = false;

% Check for existing saved agent to resume training
if doTraining && exist("DDPG_Parking_Agent_Trained.mat", "file")
    load("DDPG_Parking_Agent_Trained.mat", "agent");
    disp(">>> Agente DDPG detectado: Cargando pesos anteriores para continuar el entrenamiento.");
end

if doTraining

    % Disable UE and point cloud visualization
    setVisualizationOptions(UEViz="off",PCViz="off"); 

    % Clear visualizer to prevent issues with parallel workers
    if exist('visualizer', 'var')
        clear visualizer;
    end

    % If a GPU device is available, enable it for agent training
    agent = setDeviceForAgentTraining(agent); 

    % Start training agent
    trainingResult = train(agent,env,trainOpts); 

    % Save the trained agent
    if strcmp(algorithmType, "DDPG")
        save("DDPG_Parking_Agent_Trained.mat","agent");
    else
        save("SAC_Parking_Agent_v2.mat","agent");
    end

else
        % Modelo que quiero usar en la simulacion
        load("SAC_Parking_Agent_v2.mat","agent");
   
end
%% 
% 
%% Simulate Parking Task
% To validate the trained agent, simulate the model and observe the parking 
% maneuver across multiple parking spots. Enable both Unreal Engine and 
% point cloud visualization to get a more complete view of the vehicle's behavior.

setVisualizationOptions(UEViz="on",PCViz="on");

% Define the list of parking spots you want to simulate (valid indices: 1 to 23)
spotsToSimulate = [20, 6, 17, 1, 12]; 

for i = 1:length(spotsToSimulate)
    freeSpotIndex = spotsToSimulate(i);
    fprintf('\n=== Iniciando Simulación %d de %d: Plaza de aparcamiento libre: %d ===\n', ...
        i, length(spotsToSimulate), freeSpotIndex);
    
    % Update target pose for the new free spot
    egoTargetPose = parkingLot.findGoalPose(vehiclePose, freeSpotIndex);
    
    % Reset vehicle pose and update green/red spots in the 2D Visualizer
    if exist('visualizer', 'var') && isvalid(visualizer)
        visualizer.resetVehicle(egoInitialPose, freeSpotIndex, 0, []);
    end
    
    % Place actor vehicles in Unreal Engine and clear the target spot
    setupActorVehicles(mdl, freeSpotIndex);
    
    % Run simulation
    sim(mdl);
    
    % Pause briefly between simulations to observe the result
    pause(2);
end
%% 
% To view the trajectory graphically, open the Ego Vehicle Pose scope.

open_system(mdl + "/Vehicle Dynamics and Sensing/" + ...
    "Ego Vehicle Model/Ego Vehicle Pose")
%% 
% 
% 
% _Copyright 2023 The MathWorks, Inc._
%% Local Functions

function agent = setDeviceForAgentTraining(agent)
% Determine whether a GPU device is available and
% enable it for training if so.

    try gpuDevice;
        critic = getCritic(agent);
        critic(1).UseDevice = "gpu";
        setCritic(agent, critic);
    
        actor = getActor(agent);
        actor(1).UseDevice = "gpu";
        setActor(agent, actor);
    
        disp('GPU device found, using GPU for agent training.')
    catch ME
        disp('No GPU device found, using CPU for agent training.')
    end
end

function setVisualizationOptions(options)
%   This function takes two inputs, UEViz and PCViz.
%   UEViz and PCViz are both Boolean scalars that enable or
%   disable Unreal Engine visualization 
%   and point cloud visualization, respectively. 
    
    arguments
        options.UEViz {mustBeTextScalar} = "on"
        options.PCViz {mustBeTextScalar} = "on"
    end


    if options.UEViz == "on"
        set_param(strcat(bdroot, ...
                "/Vehicle Dynamics and Sensing/" + ...
                "Unreal Engine Visualization and Sensing" ), ...
            enableUEViz="on");
    else
        set_param(strcat(bdroot, ...
                "/Vehicle Dynamics and Sensing/" + ...
                "Unreal Engine Visualization and Sensing" ), ...
            enableUEViz="off");
    end
    
    if options.PCViz == "on"
        set_param(strcat(bdroot, ...
                "/Vehicle Dynamics and Sensing/" + ...
                "Unreal Engine Visualization and Sensing" ), ...
            enablePCViz="on");
    else 
        set_param(strcat(bdroot, ...
                "/Vehicle Dynamics and Sensing/" + ...
                "Unreal Engine Visualization and Sensing" ), ...
            enablePCViz="off");
    end
end